### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by E-Dreamer-LQ** [ChrisAllenMing/GPA-detection#1]
Hello , Could you provide some dataset  download link that you used ?  Thanks.

**Comment by ChrisAllenMing** [comment]
1. [Cityscapes & Foggy Cityscapes](https://www.cityscapes-dataset.com/)
    p.s. Transform original segmentation annotations to detection formats using these [codes](https://jbox.sjtu.edu.cn/l/KnHCR2).
2. [SIM 10k](https://fcav.engin.umich.edu/projects/driving-in-the-matrix)
3. [KITTI](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d)
