### ISSUE TITLE
Can you please show the structure of dataset directories?

### ISSUE THREAD

**Issue by pylpyl** [ChrisAllenMing/GPA-detection#13]
Thank you for your sharing! Yet I have a minor question about the structure of dataset directories.
For example, where shall I put the images and annotations of the CityScapes dataset? Should I put all images in one folder or put the Train images and Val images in two independent folders respectively? And where to put the annotations?
Of course one can guess the directory structure by reading .py files in lib/datasets. But showing the strucure will make it easier to quickly try this code out and see the result before any modification of code.
Thank you for your valuable work and code!

**Comment by ChrisAllenMing** [comment]
Hi, thanks for the question. You can structure your data folder as follows (suppose the main data direction is './data/'):
```
/data
 └── city
     ├── img_train
     ├── img_test
     ├── anno_train
     ├── anno_test
     ├── train.txt
     ├── test.txt
 ├── sim10k
 ├── kitti
```
where 'train.txt' ('test.txt') lists all the filename for the training (test) images, e.g. 0001, 0002, etc., and the filename of annotation is the same as that of the corresponding image.

**Comment by pylpyl** [comment]
> Hi, thanks for the question. You can structure your data folder as follows (suppose the main data direction is './data/'):
> 
> ```
> /data
>  └── city
>      ├── img_train
>      ├── img_test
>      ├── anno_train
>      ├── anno_test
>      ├── train.txt
>      ├── test.txt
>  ├── sim10k
>  ├── kitti
> ```
> 
> where 'train.txt' ('test.txt') lists all the filename for the training (test) images, e.g. 0001, 0002, etc., and the filename of annotation is the same as that of the corresponding image.

That will be helpful. Thanks for your reply!
