### ISSUE TITLE
A keyerror raised in roidb.py when training

### ISSUE THREAD

**Issue by pylpyl** [ChrisAllenMing/GPA-detection#14]
I prepared the dataset following the instruction. However, an error raised when I'm trying to train the model.

I tried

> CUDA_VISIBLE_DEVICES=2 python train_baseline.py --dataset sim10k --model_config baseline --net res50 --bs 3 --nw 1 --epochs 10 --lr 0.001 --lr_decay_step 6 --lr_decay_gamma 0.1 --cuda

and

> CUDA_VISIBLE_DEVICES=2 python train_GPA.py --dataset sim10k --tgt_dataset city --model_config gcn_adapt --mode gcn_adapt --rpn_mode gcn_adapt --net res50 --bs 3 --nw 1 --epochs 10 --lr 0.001 --lr_decay_step 6 --lr_decay_gamma 0.1 --warm_up 200 --da_weight 1.0 --rpn_da_weight 1.0 --cuda

Both training raised the keyerror:

> Traceback (most recent call last):
  File "train_baseline.py", line 234, in <module>
    imdb, roidb, ratio_list, ratio_index = combined_roidb(args.imdb_name)
  File "./lib/roi_data_layer/roidb.py", line 130, in combined_roidb
    ratio_list, ratio_index = rank_roidb_ratio(roidb)
  File "./lib/roi_data_layer/roidb.py", line 56, in rank_roidb_ratio
    width = roidb[i]['width']
KeyError: 'width'

My sim10k dataset is like:

> data/sim10k
  Annotations_test
  Annotations_train
  JPEGImages_test
  JPEGImages_train
  train.txt
  test.txt

and the content in train.txt is like:

> 3384911
3388793
3387502
3399389
3395308
...

There is no modification to the code. I met the error justing when trying to run the original code. Is there anything wrong with my dataset or something?

**Comment by ChrisAllenMing** [comment]
You can first make sure that the dataloader you use is './lib/datasets/sim10k.py', and then ensure that your program enter the 'prepare_roidb' function in './lib/roi_data_layer/roidb.py', since this function assigns roidb with the key 'width'.

**Comment by pylpyl** [comment]
Thanks for your reply. I will check it.

**Comment by pylpyl** [comment]
Thanks. The problem is solved.
It seems the code requires all the 10000 images of sim10k to be in the JPEGImages_train folder. I encountered this problem because I put 9000 images in the JPEGImages_train folder and 1000 in the JPEGImages_test folder.
