### ISSUE TITLE
Is this a mistake?

### ISSUE THREAD

**Issue by pylpyl** [ChrisAllenMing/GPA-detection#15]
Hi.
I met the following problem:

> Traceback (most recent call last):
  File "train_baseline.py", line 366, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/puyanglin/anaconda3/envs/gpa3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "./lib/model/faster_rcnn/faster_rcnn.py", line 53, in forward
    rois, rpn_loss_cls, rpn_loss_bbox, _, _ = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
ValueError: not enough values to unpack (expected 5, got 4)

In line 53 of ./lib/model/faster_rcnn/faster_rcnn.py it receives 5 values:

> rois, rpn_loss_cls, rpn_loss_bbox, _, _ = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)

However, the forward method in ./lib/model/rpn/rpn.py returns only 4 values when training:

> return rois, self.rpn_loss_cls, self.rpn_loss_box, rpn_cls_prob_

I modified line 53 of ./lib/model/faster_rcnn/faster_rcnn.py into:

> rois, rpn_loss_cls, rpn_loss_bbox, _ = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)

and the problem is gone.
Is this a code mistake? Thanks.

**Comment by ChrisAllenMing** [comment]
Yeah, it's a code error for the baseline model. We forgot to modify this part when fixing the bugs for adaptive faster rcnn.

**Comment by Francis0625** [comment]
The code error has been fixed.
