### ISSUE TITLE
Providing Trained Models 

### ISSUE THREAD

**Issue by frezaeix** [ChrisAllenMing/GPA-detection#4]
Hi,

Thank you for sharing your code; Is it possible for you to share your trained models on different datasets too?

**Comment by ChrisAllenMing** [comment]
We provide the models trained on three cross-domain detection tasks, i.e. synthetic to real, normal to foggy and cross camera adaptation. The link of models is as follows: [Google Drive](https://drive.google.com/drive/folders/1eOmONO8wpKFFQFTSwrGknHrLCWhd3ahw?usp=sharing).

**Comment by wennyuhey** [comment]
Thanks for sharing the models, but I only got 33.86 mAP doing cross-domain detection on cityscapes to foggy_cityscapes task, is there any arguement I need to specify in the test script before testing the pretrained model on fog_city dataset?

**Comment by ChrisAllenMing** [comment]
Hi,
In the cityscapes to foggy cityscapes task, we use the foggy images with parameter 0.01 for training and testing. I think your result may be due to the different selection of foggy images for evaluation.
