### ISSUE TITLE
Class-imbalance-aware Adaptation Training

### ISSUE THREAD

**Issue by czzbb** [ChrisAllenMing/GPA-detection#5]
Hi，thanks for sharing your code first! But I have two questions about your code.
1. I didn't see anything about `p_k` and `a_k`, which is equation 6 and 7 in your paper.
2. The way you compute intra and inter loss in [code](https://github.com/ChrisAllenMing/GPA-detection/blob/34a987ac9b71718f6d66465078a9d8ec9f9482c7/lib/model/adaptive_faster_rcnn/faster_rcnn.py#L277) is different from equation 8-9 in your paper. Especially [inter loss](https://github.com/ChrisAllenMing/GPA-detection/blob/34a987ac9b71718f6d66465078a9d8ec9f9482c7/lib/model/adaptive_faster_rcnn/faster_rcnn.py#L287)

**Comment by ChrisAllenMing** [comment]
Hi, thanks for pointing out these defects. We response as follows:
1. Considering the close correlation with one future work of us, we have to exclude the code of balancing training in this repo, At present, this repo mainly provides the implementation of graph-based region aggregation.
2. In this implementation of inter loss, compared with the equation in the paper, we add a balancing factor " ((m - d(c_i, c_j)) / m)^2 ", which, we find afterward, works better in the settings with single foreground class.
