### ISSUE TITLE
dataloader_val for sim10 to city?

### ISSUE THREAD

**Issue by frezaeix** [ChrisAllenMing/GPA-detection#6]
Hey,

I have a minor question, do you use all the sim10k images for "train"? or you have a val subset too?

Why do you have a dataloader_val for the source data in train_GPA?

**Comment by ChrisAllenMing** [comment]
Hi,
We randomly split the sim10k dataset into training and test splits with a ratio of 8:2, since we also evaluate the performance of task cityscapes->sim10k during our development.

**Comment by frezaeix** [comment]
> Hi,
> We randomly split the sim10k dataset into training and test splits with a ratio of 8:2, since we also evaluate the performance of task cityscapes->sim10k during our development.

I see, thanks.
