### ISSUE TITLE
code error?

### ISSUE THREAD

**Issue by czzbb** [ChrisAllenMing/GPA-detection#7]
In your [code](https://github.com/ChrisAllenMing/GPA-detection/blob/34a987ac9b71718f6d66465078a9d8ec9f9482c7/lib/model/adaptive_faster_rcnn/faster_rcnn.py#L161),  I think `pooled_feat` and `tgt_pooled_feat` should be `pooled_feat_ ` and `tgt_pooled_feat_ `,  respectively. Am I right?

**Comment by ChrisAllenMing** [comment]
Thanks for pointing this out! Yeah, this is a mistake when we reconstituted the code for release, and we have fixed it now. We sincerely apologize for the confusion brought to you by this mistake.

**Comment by czzbb** [comment]
another [code error](https://github.com/ChrisAllenMing/GPA-detection/blob/d63d3cd8a76523615c288cceb676f75967f5914e/lib/model/adaptive_faster_rcnn/faster_rcnn.py#L227):  `rois` and `tgt_rois` should be `rois_select` and `tgt_rois_select` ?
What's more, I wonder why you change `pos_ratio` from 0.5 to 0.25 and  `rpn_bs` from 256 to 128.
